### ISSUE TITLE
VS 17.12.1 "Clear all in document" works with delay and not every time

### ISSUE THREAD

**Issue by vsopko** [mrlacey/VSHighlighter#2]
If use "Clear all in document" option - colored dot mark on left vertical bar (where breakpoints is) disappears, but highlighted line in code editor is still with background color. And it is removed/rerendered only if you scroll document in a way when selected text is not visible on the screen.

https://github.com/user-attachments/assets/d21a7a75-f4bb-4e6e-a9c3-66ca095a46f7

**Comment by mrlacey** [comment]
Highlights not clearing immediately is possibly related to https://developercommunity.visualstudio.com/t/ITaggerGetTags-in-the-VSSDK-appears-t/10798945

**Comment by mrlacey** [comment]
v1.3 (now in the marletplace) should fix this
